import { useQuery } from '@tanstack/react-query'
import { Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { TransactionModal } from '../components/TransactionModal'
import { Button, Card, EmptyState, LoadingState } from '../components/ui'
import { financeApi } from '../services/api'
import type { Transaction } from '../types'
import { currency, dateFormat } from '../utils/format'
export function TransactionsPage(){const [page,setPage]=useState(1),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<Transaction>();const categories=useQuery({queryKey:['categories'],queryFn:financeApi.categories});const list=useQuery({queryKey:['transactions',page,search],queryFn:()=>financeApi.transactions({page,search})});if(list.isLoading||categories.isLoading)return <LoadingState/>;const refresh=()=>{setModal(false);setEditing(undefined);list.refetch()};return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl font-bold">Transações</h2><p className="text-muted">Acompanhe cada entrada e saída.</p></div><Button onClick={()=>setModal(true)}><Plus className="mr-2 inline" size={18}/>Nova transação</Button></div><Card><div className="mb-5 flex gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-subtle" size={18}/><input className="pl-10" placeholder="Buscar por descrição" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label></div>{list.data?.items.length?<div className="overflow-x-auto"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th>Tipo</th><th className="text-right">Valor</th><th/></tr></thead><tbody>{list.data.items.map(t=><tr key={t.id}><td className="font-medium">{t.description}</td><td><span className="badge" style={{borderColor:t.category.color}}>{t.category.name}</span></td><td>{dateFormat(t.date)}</td><td>{t.type==='INCOME'?'Receita':'Despesa'}</td><td className={`text-right font-bold ${t.type==='INCOME'?'text-neon':'text-danger'}`}>{t.type==='INCOME'?'+':'-'} {currency(t.amount)}</td><td><button onClick={()=>{setEditing(t);setModal(true)}} aria-label="Editar"><Pencil size={17}/></button><button className="ml-3 text-danger" onClick={async()=>{if(confirm('Tem certeza que deseja excluir esta transação?')){await financeApi.deleteTransaction(t.id);list.refetch()}}} aria-label="Excluir"><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>:<EmptyState/>}{(list.data?.total_pages||0)>1&&<div className="mt-5 flex justify-end gap-2"><Button className="bg-panel text-white hover:bg-card" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</Button><Button className="bg-panel text-white hover:bg-card" disabled={page===(list.data?.total_pages||0)} onClick={()=>setPage(page+1)}>Próxima</Button></div>}</Card>{modal&&categories.data&&<TransactionModal categories={categories.data} transaction={editing} onClose={refresh} onSave={async data=>{if(editing)await financeApi.updateTransaction(editing.id,data);else await financeApi.createTransaction(data);refresh()}}/>}</div>}
